# hash:sha256:18059f8c25191cabc9797cff5ff86de91c84818dbd0bb30c3900ae1710e28ef3
FROM registry.acmecorp-edge.codeocean.com/codeocean/mambaforge3:22.11.1-4-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
